openapi: 3.0.0
info:
  version: '1.0.0'
  title: File API

paths:
  /api/status:
    get:
      summary: Check API status
      description: Get the current status of the API
      responses:
        '200':
          description: The API is functional

  /api/files:
    post:
      summary: File upload
      description: Upload a file to the server
      responses:
        '200':
          description: File upload successful
        '400':
          description: Invalid file type or size limit exceeded

  /api/files/metas:
    get:
      summary: Every file metadata
      description: Returns all available file tokens as a list
      responses:
        '200':
          description: returns a list of all available files metadata
    post:
      summary: File metadata per token(s)
      description: Returns metadata for files based on provided tokens
      responses:
        '200':
          description: Returns a list of file metadata
        '400':
          description: Invalid token format


  /api/files/{get_token}:
    get:
      summary: File download
      description: Return the file with the corresponding UUID
      responses:
        '200':
          description: Returns the file
        '400':
          description: Invalid token

  /api/files/{delete_token}:
    delete:
      summary: File deletion
      description: Deletes the file corresponding to the token
      responses:
        '200':
          description: File is deleted
        '400':
          description: Token can't be traced to a file


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: |
        Basic authentication using username and password.
        Provide your credentials in the Authorization header as follows:
        ```
        Authorization: Basic <base64-encoded-credentials>
        ```